# Generated by Django 3.2.3 on 2021-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20210517_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
