# Generated by Django 3.2.3 on 2021-05-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
    ]
