# Generated by Django 3.2.3 on 2021-05-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20210517_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
