# Generated by Django 3.2.3 on 2021-05-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_remove_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='downvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='downvoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='upvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='upvoted',
            field=models.BooleanField(default=False),
        ),
    ]
