# Generated by Django 3.2.3 on 2021-05-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_auto_20210518_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='content',
            name='downvoted',
        ),
        migrations.RemoveField(
            model_name='content',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='content',
            name='upvoted',
        ),
    ]
