# Generated by Django 3.2.3 on 2021-05-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('name', models.CharField(default='', max_length=150)),
                ('content_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True)),
                ('has_upvoted', models.BooleanField(default=False)),
                ('has_downvoted', models.BooleanField(default=False)),
            ],
        ),
    ]
